# grabtv
IPTV client to download, search and play movies and TV series

## Introduction into development thoughts on project start

## Prerequisite 

This application supported Operating Systems

 * Windows 11
 * Rocky Linux release 9.4
 * Ubuntu 22.04.5 LTS

 For other linux distributions, you can build the application from source code.

 ## Deployment

### Windows

When building and deploying the application on Windows, we use `windeployqt` 
to deploy the application. 

We do that by running the following command in the terminal:

[source,bash]
windeployqt --release --no-translations --no-angle --no-opengl-sw --no-system-d3d-compiler --no-compiler-runtime --no-webkit2 --no-qml-debug grabtv.exe


### Rocky Linux

When building and deploying the application on Rocky Linux, we use `AppImage`

We do that by running the following command in the terminal:

[source,bash]
appimagetool grabtv.AppDir grabtv.AppImage

### Ubuntu

When building and deploying the application on Ubuntu, we use `AppImage`

We do that by running the following command in the terminal:

[source,bash]
appimagetool grabtv.AppDir grabtv.AppImage





## Installation

### Windows

To install the application on Windows, download the installer from the website and run it.

### Rocky Linux

To install the application on Rocky Linux, download the AppImage from the website and run it.

### Ubuntu

To install the application on Ubuntu, download the AppImage from the website and run it.





