name: Bug report - form
description: Create a bug report from a form to help me improve Grab TV.
title: "[Bug]:"
labels: ["bug"]
assignees:
  - guttih
body:
- type: markdown
  attributes:
    value: |
      Bug report on the Grab TV - Visual Studio Code Extension
- type: input
  id: contact
  attributes:
    label: Contact Details
    description: How can I get in touch with you if I need more info?
    placeholder: ex. email@example.com
  validations:
    required: false
- type: input
  id: summary
  attributes:
    label: Summary
    description: Short summary of what is going on or to provide context
  validations:
    required: false
- type: textarea
  id: what-happened
  attributes:
    label: What happened?    
    description: | 
      - **Additional context** Add any other context or screenshots about the bug here.
    placeholder: |
     Please write your bug report here 
    value: 
  validations:
    required: true
- type: textarea
  id: reproduce
  attributes:
    label: Steps To Reproduce
    description: |
      1.  First I...
      2.  Then...
      
      - **Additional context** Add any other context or screenshots about the bug here.
      
    placeholder: |
     Please describe to me how I can reproduce the bug, so I can find out how to fix it 
    value: 
  validations:
    required: false
- type: textarea
  id: expectedx
  attributes:
    label: Expected result
    description: |
      Describe what should have happened
        - **Additional context** Add any other context or screenshots about the bug here.
     
    placeholder:  |
     Please write your request here
    value: 
  validations:
    required: false
- type: dropdown
  id: version
  attributes:
    label: Version - Grab TV desktop application
    description:  In Grab TV application menu, select "Help" > "About" and provide the version number you see there
    options:
      - 0.0.1
      - 1.0.0
  validations:
    required: true
- type: dropdown
  id: os
  validations:
    required: true
  attributes:
    label: What operating system  are you seeing the problem on?
    multiple: true
    options:
      - 'Windows 10'
      - 'Windows 11'
      - 'Linux - Rocky linux 9'
      - 'Linux - Ubuntu'
      - 'Linux - other'
      - 'Other'
- type: input
  id: os_other
  attributes:
    label: Other operating system(s)
    description: Operating system(s) not in the options above can be added here
    placeholder: Other OS
- type: textarea
  id: notes
  attributes:
    label: Notes 
    description: Is there something else? 
    placeholder: | 
                  Something you want to add?  
                  Please do, I would appreciate it :)
    render: shell
