name: Feature request
description: Suggest an idea for the Grab TV desktop application
title: "[Feature]:"
labels: ["enhancement"]
assignees:
  - guttih
body:
- type: markdown
  attributes:
    value: |
      Feature request on the Grab TV - Desktop Application
- type: input
  id: contact
  attributes:
    label: Contact Details
    description: How can I get in touch with you if I need more info?
    placeholder: ex. email@example.com
  validations:
    required: false
- type: textarea
  id: why
  attributes:
    label: Why do you want this feature?
    description: |
     Ideas to help you along, writing your request
     - Is your feature request related to a problem? Please describe.
       A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]
     - Describe the solution you'd like
       A clear and concise description of what you want to happen.
     - Describe alternatives you've considered
       A clear and concise description of any alternative solutions or features you've considered.
     - Additional context
     Add any other context or screenshots about the feature request here. 
     
    placeholder:  |
     Please write your request here
    value: 
  validations:
    required: true
- type: dropdown
  id: os
  validations:
    required: false
  attributes:
    label: If this feature is Operating System specific, please select it?
    multiple: true
    options:
      - 'Windows 10'
      - 'Windows 11'
      - 'Linux - Rocky linux 9'
      - 'Linux - Ubuntu'
      - 'Linux - other'
      - 'Other'
- type: input
  id: os_other
  attributes:
    label: Other operating system
    description: Operating system not in the options above and/or more details about your OS
    placeholder: Other OS
- type: textarea
  id: notes
  attributes:
    label: Notes
    description: Is there something else? 
    placeholder: | 
                  Something you want to add?  
                  Please do, I would appreciate it :)
    render: shell
      
     
