:doctitle: Development - {system-name}
:author: Gudjon Holm
:docinfo: shared
:doctype: book
:encoding: utf-8
:lang: en
:toc: left
:toc-title: Table of Contents
:toclevels: 3
:numbered:
:experimental:
:xrefstyle: short
:imagesdir: images
:chapter-signifier:
:system-name: Grab TV
:stylesdir: ../styles
:stylesheet: style.css
:git-repo: git@github.com:guttih/grabtv.git

= Development

This document provides information on development practices and procedures for the project.

This project needs to be developed on a Linux distribution, such as Rocky Linux, Ubuntu, or other Linux distributions.
Developing on window can only be done by using the Windows Subsystem for Linux (WSL) or a virtual machine.

== Prerequisite

The application supports the following Operating Systems:

* Windows 11
* Rocky Linux release 9.4
* Ubuntu 22.04.5 LTS
* Other Linux distributions (build from source code)

To develop the application, you will require:

. Desktop version of Qt 6.6 or later
. CMake
. A compatible C++ compiler (e.g., GCC, Clang, or MinGW on Windows)
. Necessary dependencies based on your Linux distribution

For developing the application on Rocky Linux 9, perform the following steps:

. Install Qt6.6 Desktop version or later

== Deployment

=== Windows

When building and deploying the application on Windows, you will need to use qtcreator to build configure and build the application.

=== Rocky Linux, Ubuntu, and Other Linux Distributions

=== Rocky Linux Preparations

1. Install Development Tools:
+
[source,bash]
----
sudo dnf groupinstall "Development Tools"
sudo dnf install cmake gcc-c++ mingw64-gcc-c++ sqlite
----

2. Install Qt 6.8:
To install Qt in your Rocky Linux, it's recommended to go to the [Qt Official Download Page](hhttps://www.qt.io/download-open-source), download the Open Source version and follow their installation guide.

3. Clone the Repository:
Navigate to the desired place in your filesystem and clone the repository.
+
[source,bash, subs="attributes"]
----
git clone {git-repo}
----

4. Dependencies for Cross Compilation:
This step is necessary if planning to compile your program for Windows OS.
[source,bash]
----
sudo dnf install mingw64-qt5-qmake #Not sure if this is needed
----

== Building the Project

Once that's set up, you can setup your working directory as follows:

2. Create a new directory for the build and navigate into it and run the following commands:
.. Normally 
+
[source,bash]
----
mkdir -p build && cd build
cmake ..
make
----

.. One-liner
+
[source,bash]
----
rm -rf build/*; mkdir -p build  && cd build && cmake .. && make && cd .. && ls build/grabtv
----

== Git workflow

include::developmentGit.adoc[]
